// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Migraciones_Trasporte.src.Shared.Context;

#nullable disable

namespace Migraciones_Trasporte.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260412042344_DocumentCategory")]
    partial class DocumentCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Migraciones_Trasporte.src.Modules.Document_Category.Infrastructure.Entity.DocumentCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("description");

                    b.Property<Guid?>("DocumentCategoryEntityId")
                        .HasColumnType("char(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("DocumentCategoryEntityId");

                    b.ToTable("document_category", (string)null);
                });

            modelBuilder.Entity("Migraciones_Trasporte.src.Modules.Document_Category.Infrastructure.Entity.DocumentCategoryEntity", b =>
                {
                    b.HasOne("Migraciones_Trasporte.src.Modules.Document_Category.Infrastructure.Entity.DocumentCategoryEntity", null)
                        .WithMany("DocumentCategory")
                        .HasForeignKey("DocumentCategoryEntityId");
                });

            modelBuilder.Entity("Migraciones_Trasporte.src.Modules.Document_Category.Infrastructure.Entity.DocumentCategoryEntity", b =>
                {
                    b.Navigation("DocumentCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
