// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Migraciones_Trasporte.src.Shared.Context;

#nullable disable

namespace Migraciones_Trasporte.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260412193151_NotificationType")]
    partial class NotificationType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Migraciones_Trasporte.src.Modules.Companies_Status.Infrastructure.Entity.CompaniesStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("id");

                    b.Property<Guid?>("CompaniesStatusEntityId")
                        .HasColumnType("char(64)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CompaniesStatusEntityId");

                    b.ToTable("companies_status", (string)null);
                });

            modelBuilder.Entity("Migraciones_Trasporte.src.Modules.Document_Category.Infrastructure.Entity.DocumentCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("description");

                    b.Property<Guid?>("DocumentCategoryEntityId")
                        .HasColumnType("char(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("DocumentCategoryEntityId");

                    b.ToTable("document_category", (string)null);
                });

            modelBuilder.Entity("Migraciones_Trasporte.src.Modules.Documents_Status.Infrastructure.Entity.DocumentStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("description");

                    b.Property<Guid?>("DocumentStatusEntityId")
                        .HasColumnType("char(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("DocumentStatusEntityId");

                    b.ToTable("document_status", (string)null);
                });

            modelBuilder.Entity("Migraciones_Trasporte.src.Modules.Notification_Type.Infrastructure.Entity.NotificationTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<Guid?>("NotificationTypeEntityId")
                        .HasColumnType("char(64)");

                    b.HasKey("Id");

                    b.HasIndex("NotificationTypeEntityId");

                    b.ToTable("notification_type", (string)null);
                });

            modelBuilder.Entity("Migraciones_Trasporte.src.Modules.Person_Status.Infrastructure.Entity.PersonStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<Guid?>("PersonStatusEntityId")
                        .HasColumnType("char(64)");

                    b.HasKey("Id");

                    b.HasIndex("PersonStatusEntityId");

                    b.ToTable("person_status", (string)null);
                });

            modelBuilder.Entity("Migraciones_Trasporte.src.Modules.Vehicules_Status.Infrastructure.Entity.VehiculesStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("char(64)")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<Guid?>("VehiculesStatusEntityId")
                        .HasColumnType("char(64)");

                    b.HasKey("Id");

                    b.HasIndex("VehiculesStatusEntityId");

                    b.ToTable("vehicules_status", (string)null);
                });

            modelBuilder.Entity("Migraciones_Trasporte.src.Modules.Companies_Status.Infrastructure.Entity.CompaniesStatusEntity", b =>
                {
                    b.HasOne("Migraciones_Trasporte.src.Modules.Companies_Status.Infrastructure.Entity.CompaniesStatusEntity", null)
                        .WithMany("CompaniesStatus")
                        .HasForeignKey("CompaniesStatusEntityId");
                });

            modelBuilder.Entity("Migraciones_Trasporte.src.Modules.Document_Category.Infrastructure.Entity.DocumentCategoryEntity", b =>
                {
                    b.HasOne("Migraciones_Trasporte.src.Modules.Document_Category.Infrastructure.Entity.DocumentCategoryEntity", null)
                        .WithMany("DocumentCategory")
                        .HasForeignKey("DocumentCategoryEntityId");
                });

            modelBuilder.Entity("Migraciones_Trasporte.src.Modules.Documents_Status.Infrastructure.Entity.DocumentStatusEntity", b =>
                {
                    b.HasOne("Migraciones_Trasporte.src.Modules.Documents_Status.Infrastructure.Entity.DocumentStatusEntity", null)
                        .WithMany("DocumentsStatus")
                        .HasForeignKey("DocumentStatusEntityId");
                });

            modelBuilder.Entity("Migraciones_Trasporte.src.Modules.Notification_Type.Infrastructure.Entity.NotificationTypeEntity", b =>
                {
                    b.HasOne("Migraciones_Trasporte.src.Modules.Notification_Type.Infrastructure.Entity.NotificationTypeEntity", null)
                        .WithMany("NotificationType")
                        .HasForeignKey("NotificationTypeEntityId");
                });

            modelBuilder.Entity("Migraciones_Trasporte.src.Modules.Person_Status.Infrastructure.Entity.PersonStatusEntity", b =>
                {
                    b.HasOne("Migraciones_Trasporte.src.Modules.Person_Status.Infrastructure.Entity.PersonStatusEntity", null)
                        .WithMany("PersonStatus")
                        .HasForeignKey("PersonStatusEntityId");
                });

            modelBuilder.Entity("Migraciones_Trasporte.src.Modules.Vehicules_Status.Infrastructure.Entity.VehiculesStatusEntity", b =>
                {
                    b.HasOne("Migraciones_Trasporte.src.Modules.Vehicules_Status.Infrastructure.Entity.VehiculesStatusEntity", null)
                        .WithMany("VehiculesStatus")
                        .HasForeignKey("VehiculesStatusEntityId");
                });

            modelBuilder.Entity("Migraciones_Trasporte.src.Modules.Companies_Status.Infrastructure.Entity.CompaniesStatusEntity", b =>
                {
                    b.Navigation("CompaniesStatus");
                });

            modelBuilder.Entity("Migraciones_Trasporte.src.Modules.Document_Category.Infrastructure.Entity.DocumentCategoryEntity", b =>
                {
                    b.Navigation("DocumentCategory");
                });

            modelBuilder.Entity("Migraciones_Trasporte.src.Modules.Documents_Status.Infrastructure.Entity.DocumentStatusEntity", b =>
                {
                    b.Navigation("DocumentsStatus");
                });

            modelBuilder.Entity("Migraciones_Trasporte.src.Modules.Notification_Type.Infrastructure.Entity.NotificationTypeEntity", b =>
                {
                    b.Navigation("NotificationType");
                });

            modelBuilder.Entity("Migraciones_Trasporte.src.Modules.Person_Status.Infrastructure.Entity.PersonStatusEntity", b =>
                {
                    b.Navigation("PersonStatus");
                });

            modelBuilder.Entity("Migraciones_Trasporte.src.Modules.Vehicules_Status.Infrastructure.Entity.VehiculesStatusEntity", b =>
                {
                    b.Navigation("VehiculesStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
